### ISSUE TITLE
QA tangerine job is restarting though the job is success

### ISSUE THREAD

**Issue by HarikaVuppala** [zeagler/tangerine#32]
This is happening on the `ICAT-Main` QA job.

If you look at the history tab, the job ran today 4 times until now starting at 5:00 AM. All the 4 logs shows success.

Restartable flag on the job is False. I am unable to understand the reason for this issue so submitting an issue. I don't have rights to assign it so tagging @zeagler

**Comment by zeagler** [comment]
This was caused by the exit code being lost and Tangerine assumed the container exited abnormally. Exit codes are much more reliable with the latest update and the cause of failures are better communicated.
