### ISSUE TITLE
Keep Hosts in a Database

### ISSUE THREAD

**Issue by zeagler** [zeagler/tangerine#4]
At the moment the existence of hosts is only known by Rancher. This means whenever Tangerine needs something it pings Rancher's API. By keeping a synced copy of the hosts in Tangerine's database there will be more flexibility in task-host management. Dynamic host labels can be better managed and exit codes can be communicated better. A better history of hosts can be kept. This will also help in the far future when the dependency on Rancher is removed.

- [ ] Create a row in Tangerine's database for every Rancher host
- [ ] When a task needs a host, Tangerine's database will be referenced
- [ ] Remove the host when it is removed from Rancher
- [ ] Keep a history of the host including creation and termination time

**Comment by zeagler** [comment]
Note: In the current version there is a known bug where the exit code isn't retrieved correctly. This will make retrieving the exit code more dependable.

**Comment by zeagler** [comment]
As of v0.2 agents are kept in the database along with host information.

**Comment by ManuelCalavera** [comment]
:+1: Thanks @zeagler
