### ISSUE TITLE
Issue with placing a job in ready state through Tangerine

### ISSUE THREAD

**Issue by HarikaVuppala** [zeagler/tangerine#46]
This is observed while trying to execute a tangerine task that has a dependency. 
When i added the FactBilling task to the queue using the insert/update statement, tangerine is keeping the task in the queue and not executing it even though the dependency job finished successfully.

**Comment by zeagler** [comment]
I did some further testing and found that removing the dependency unblocked it: `ICAT-ArtifactRun-DEV-FactPolicyCoverage`. I'm still looking for a reason why that dependency isn't being verified, both of these tasks were added manually with a query, correct?

**Comment by zeagler** [comment]
Inserting the task with a query caused the problem. The `next_run_time` for the dependency was set at 0, which told Tangerine that it needed to be executed. Setting it to the proper `NULL` value started the tasks as expected. I'd advise staying away from manual queries until the database is thoroughly documented, there is too much that can go wrong with improper values. For a programmatic approach the API or UI is the best bet.
