### ISSUE TITLE
Adding a dependency is causing errors

### ISSUE THREAD

**Issue by HarikaVuppala** [zeagler/tangerine#47]
I am trying to create a new task with a dependency. With the new image on QA, the dependency text box is not displaying the existing tasks when i start typing the task name. Also, after typing the dependency name manually and clicking on enter it is throwing the below error message

```
404 Not Found

Unexpected query string parameters: etp, name, image, cmd, idl, cron, state, daf, mxf, rec, desc

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 66, in __call__
    raise sys.exc_info()[1]
HTTPError: (404, 'Unexpected query string parameters: etp, name, image, cmd, idl, cron, state, daf, mxf, rec, desc')
```

**Comment by zeagler** [comment]
As you have reported this was fixed after a refresh it sounds like your session expired. The running instance of Tangerine in QA hasn't been replaced or restarted.

If this happens again after the next update with the fix from #10 I'll reopen this.

**Comment by HarikaVuppala** [comment]
Just making a note that i got this error again. Browser is already refreshed an hour ago as you know from above. Refreshing the browser made the error disappear as usual.

![capture](https://cloud.githubusercontent.com/assets/13470179/18677014/86b585b6-7f25-11e6-924b-6bb0eab1d013.PNG)

**Comment by zeagler** [comment]
I might need to gather some more information about it. The sessions expire 45 minutes after inactivity, so with an hour it is reasonable that the session expired again. Has this been an issue before today?

**Comment by HarikaVuppala** [comment]
No, faced this issue only today. I wouldn't say that my session is inactive. I am actively running the jobs through the browser.
