### ISSUE TITLE
Environment variables can't contain an equal sign

### ISSUE THREAD

**Issue by zeagler** [zeagler/tangerine#49]
Tangerine splits environment variable strings at the equal sign. Any environment variable with an `=` present is truncated, which prevents setting things like Java options.

**Comment by HarikaVuppala** [comment]
Adding more info- This is observed while setting `-Dfile.encoding=UTF-8` in the environment variables. 
As per our chat, I am going to try running the preprocess jobs without setting it as `UTF-8 is the default encoding for the JVM in the Docker container`. If it doesn't work then this is high priority. Will update you.

**Comment by HarikaVuppala** [comment]
@zeagler Ran the CPX preprocess job without explicitly setting UTF-8 and it ran without errors and loaded all the table. From my end, this is not high priority now.

**Comment by zeagler** [comment]
Fixed in 0.2.1
https://github.com/zeagler/tangerine/releases/tag/v0.2.1
