### ISSUE TITLE
Tangerine is not allowing to create a task with same name in a different job

### ISSUE THREAD

**Issue by HarikaVuppala** [zeagler/tangerine#54]
@zeagler I know you are already working on this, just creating an issue...  We have mentioned this during the walkthrough yesterday.

New image deployed to tangerine is not allowing to create a task with same name which already exists in another job.

![nameconflict](https://cloud.githubusercontent.com/assets/13470179/19566541/b3bfd084-96b8-11e6-8054-aa91106985a6.PNG)

**Comment by zeagler** [comment]
This has been modified in the latest commit 582793c. Tasks can have the same name, but only if they have different parents.
