### ISSUE TITLE
Host Failure error on QA jobs

### ISSUE THREAD

**Issue by HarikaVuppala** [zeagler/tangerine#55]
I am trying to run a task inside the `ICAT ETL` job(FactPolicyCoverage) and it initially did not start running ,it used to fail with `Host Failure` error(I tried stopping and rerunning but did not work).

After @Roberto restarted the tangerine QA host, job started execution but after execution of couple of min(~15min) job failed again with `Host Failure` error.

Creating the issue as this keeps happening and blocking me.

![capture](https://cloud.githubusercontent.com/assets/13470179/19857378/d446140a-9f53-11e6-9497-2aa9b856bb36.PNG)

**Comment by HarikaVuppala** [comment]
Tagging @zeagler

**Comment by zeagler** [comment]
This was caused by a ec2 termination when the spot price went over our bid. With the last deploy you can switch between on-demand and spot instance as needed.
