### ISSUE TITLE
Add Tangerine tags to AWS resources

### ISSUE THREAD

**Issue by ManuelCalavera** [zeagler/tangerine#56]
When Tangerine spins up resources, it would be great if we can tag these, this way we can leverage DataDog for querying resources that are being created by certain applications.

**Comment by zeagler** [comment]
The instance configurations will apply any tags to the resources it starts.

![tag](https://cloud.githubusercontent.com/assets/13981634/20851222/1c6e75ac-b8ad-11e6-894f-da308cefe582.png)

**Comment by ManuelCalavera** [comment]
Awesome! Thanks!
